import fs from 'fs';
import path from 'path';

const dictsDir = path.resolve(process.cwd(), 'src/i18n/dictionaries');

const translations = {
  ko: {
    auth: {
      login_title: "리바셀 바이오 로그인",
      login_sub: "개인 맞춤형 줄기세포 치료 프로토콜에 접근하세요.",
      email_label: "이메일 또는 연구 ID (Email or Research ID)",
      email_placeholder: "name@institution.com",
      password_label: "비밀번호 (Password)",
      password_placeholder: "••••••••",
      find_password: "비밀번호 찾기",
      secure_login: "안전한 로그인 (Secure Login)",
      or_continue: "또는 다음으로 로그인",
      new_to: "리바셀 생태계가 처음이신가요?",
      iso_badge: "ISO 27001 인증 방화벽 적용",
      enc_badge: "256-Bit 암호화 활성화",
      signup_title1: "수명 연장의 내일을",
      signup_title2: "설계합니다.",
      signup_sub: "임상적 우수성을 위해 바이오 혁신을 활용하는 전 세계 임상의 및 최고 연구원 네트워크에 지금 합류하세요.",
      tag: "생명을 위한 정밀 공학",
      cp_title: "임상적 정밀성 (Clinical Precision)",
      cp_desc: "철저하게 검증된 생물학적 프레임워크를 제공합니다.",
      ef_title: "윤리 최우선 (Ethics First)",
      ef_desc: "글로벌 개인정보 보호 규정 준수 및 최고 수준의 보안을 유지합니다.",
      portal: "가입 포털 (Registration Portal)",
      step1: "1단계 (총 3단계): 신원 검증 및 인증",
      credentials: "계정 정보 (Account Credentials)",
      prof_email: "전문가용 이메일",
      prof_email_ph: "이메일을 입력하세요",
      access_pw: "접속 비밀번호",
      access_pw_ph: "••••••••",
      personal_details: "개인 식별 정보 (Personal Details)",
      first_name: "이름 (First Name)",
      first_name_ph: "이름 입력",
      last_name: "성 (Last Name)",
      last_name_ph: "성 입력",
      affiliation: "소속 기관 (Clinical Affiliation)",
      affiliation_ph: "소속 기관명 입력",
      ecosystems: "연구 관심 분야 (Research Ecosystems)",
      health: "건강 (Health)",
      anti_aging: "항노화 (Anti-aging)",
      clinical: "임상 (Clinical)",
      create_account: "계정 생성하기 (Create Account)",
      agreement: "계정을 생성함으로써 당사의 윤리 강령 및 전문가 행동 지침에 동의하는 것으로 간주됩니다."
    },
    footer: {
      brand: "StemLink",
      copyright: "© 2024 StemLink. 생명을 위한 정밀 공학. (Precision Engineering for Life)",
      privacy: "개인정보 처리방침",
      terms: "이용약관",
      ethics: "윤리 강령",
      offices: "Global Offices"
    }
  },
  en: {
    auth: {
      login_title: "StemLink Login",
      login_sub: "Access your personalized stem cell therapy protocols.",
      email_label: "Email or Research ID",
      email_placeholder: "name@institution.com",
      password_label: "Password",
      password_placeholder: "••••••••",
      find_password: "Find Password",
      secure_login: "Secure Login",
      or_continue: "Or continue with",
      new_to: "New to our bio-ecosystem?",
      iso_badge: "ISO 27001 Certified Firewall",
      enc_badge: "256-Bit Encryption Active",
      signup_title1: "Architecting the future of",
      signup_title2: "longevity.",
      signup_sub: "Join our exclusive network of clinicians and researchers leveraging bio-tech innovation for clinical excellence.",
      tag: "Precision Engineering for Life",
      cp_title: "Clinical Precision",
      cp_desc: "Validated biological frameworks.",
      ef_title: "Ethics First",
      ef_desc: "Global privacy compliance and high-security.",
      portal: "Registration Portal",
      step1: "Step 1 of 3: Verification & Identity",
      credentials: "Account Credentials",
      prof_email: "Professional Email",
      prof_email_ph: "Enter your email",
      access_pw: "Access Password",
      access_pw_ph: "••••••••",
      personal_details: "Personal Details",
      first_name: "First Name",
      first_name_ph: "Enter first name",
      last_name: "Last Name",
      last_name_ph: "Enter last name",
      affiliation: "Clinical Affiliation",
      affiliation_ph: "Enter affiliation name",
      ecosystems: "Research Ecosystems",
      health: "Health",
      anti_aging: "Anti-aging",
      clinical: "Clinical",
      create_account: "Create Account",
      agreement: "By creating an account, you agree to our Ethics Framework and Professional Conduct guidelines."
    },
    footer: {
      brand: "StemLink",
      copyright: "© 2024 StemLink. Precision Engineering for Life.",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      ethics: "Ethics Framework",
      offices: "Global Offices"
    }
  },
  ja: {
    auth: {
      login_title: "StemLink ログイン",
      login_sub: "パーソナライズされた幹細胞治療プロトコルにアクセスします。",
      email_label: "メールまたは研究ID",
      email_placeholder: "name@institution.com",
      password_label: "パスワード",
      password_placeholder: "••••••••",
      find_password: "パスワードをお忘れですか",
      secure_login: "安全にログイン",
      or_continue: "または次でログイン",
      new_to: "RevaCellエコシステムは初めてですか？",
      iso_badge: "ISO 27001 認定ファイアウォール",
      enc_badge: "256-Bit 暗号化有効",
      signup_title1: "長寿の未来を",
      signup_title2: "設計する。",
      signup_sub: "臨床的卓越性のためにバイオ技術革新を活用する、世界中の臨床医と研究者の独占的ネットワークに今すぐ参加してください。",
      tag: "生命のための精密工学",
      cp_title: "臨床的精密さ",
      cp_desc: "徹底的に検証された生物学的フレームワークを提供します。",
      ef_title: "倫理第一",
      ef_desc: "グローバルなプライバシー規制への準拠と最高レベルのセキュリティを維持します。",
      portal: "登録ポータル",
      step1: "ステップ1（全3ステップ）：身元確認と認証",
      credentials: "アカウント情報",
      prof_email: "プロフェッショナルメール",
      prof_email_ph: "メールアドレスを入力",
      access_pw: "アクセスパスワード",
      access_pw_ph: "••••••••",
      personal_details: "個人識別情報",
      first_name: "名",
      first_name_ph: "名を入力",
      last_name: "姓",
      last_name_ph: "姓を入力",
      affiliation: "所属機関",
      affiliation_ph: "所属機関名を入力",
      ecosystems: "研究関心分野",
      health: "健康",
      anti_aging: "アンチエイジング",
      clinical: "臨床",
      create_account: "アカウントを作成",
      agreement: "アカウントを作成することにより、当社の倫理規範および専門家行動指針に同意したものとみなされます。"
    },
    footer: {
      brand: "StemLink",
      copyright: "© 2024 StemLink. 生命のための精密工学。",
      privacy: "プライバシーポリシー",
      terms: "利用規約",
      ethics: "倫理綱領",
      offices: "グローバルオフィス"
    }
  },
  zh: {
    auth: {
      login_title: "StemLink 登录",
      login_sub: "访问您的个性化干细胞治疗协议。",
      email_label: "邮箱或研究ID",
      email_placeholder: "name@institution.com",
      password_label: "密码",
      password_placeholder: "••••••••",
      find_password: "找回密码",
      secure_login: "安全登录",
      or_continue: "或使用以下方式登录",
      new_to: "初次进入生态圈？",
      iso_badge: "ISO 27001 认证防火墙",
      enc_badge: "256-Bit 加密启用",
      signup_title1: "构筑长寿之",
      signup_title2: "未来。",
      signup_sub: "加入我们的独家临床医生和研究人员网络，利用生物技术创新实现卓越临床表现。",
      tag: "生命的精密工程",
      cp_title: "临床精准性",
      cp_desc: "经过验证的生物学框架。",
      ef_title: "伦理至上",
      ef_desc: "遵守全球隐私法规并保持最高级别的安全。",
      portal: "注册门户",
      step1: "步骤1（共3步）：身份验证",
      credentials: "账户凭据",
      prof_email: "专业电子邮件",
      prof_email_ph: "输入您的电子邮件",
      access_pw: "访问密码",
      access_pw_ph: "••••••••",
      personal_details: "个人信息",
      first_name: "名",
      first_name_ph: "输入您的名",
      last_name: "姓",
      last_name_ph: "输入您的姓",
      affiliation: "所属机构",
      affiliation_ph: "输入您的所属机构名称",
      ecosystems: "研究生态系统",
      health: "健康",
      anti_aging: "抗衰老",
      clinical: "临床",
      create_account: "创建账户",
      agreement: "创建帐户即表示您同意我们的道德准则和专业行为准则。"
    },
    footer: {
      brand: "StemLink",
      copyright: "© 2024 StemLink. 生命的精密工程。",
      privacy: "隐私政策",
      terms: "服务条款",
      ethics: "伦理准则",
      offices: "全球办事处"
    }
  },
  vi: {
    auth: {
      login_title: "Đăng nhập StemLink",
      login_sub: "Truy cập phác đồ liệu pháp tế bào gốc được cá nhân hóa của bạn.",
      email_label: "Email hoặc ID nghiên cứu",
      email_placeholder: "name@institution.com",
      password_label: "Mật khẩu",
      password_placeholder: "••••••••",
      find_password: "Tìm mật khẩu",
      secure_login: "Đăng nhập an toàn",
      or_continue: "Hoặc tiếp tục với",
      new_to: "Bạn mới tham gia hệ sinh thái?",
      iso_badge: "Tường lửa được chứng nhận ISO 27001",
      enc_badge: "Đã bật mã hóa 256-Bit",
      signup_title1: "Thiết kế tương lai của",
      signup_title2: "sự trường thọ.",
      signup_sub: "Tham gia mạng lưới độc quyền gồm các bác sĩ lâm sàng và nhà nghiên cứu sử dụng đổi mới công nghệ sinh học cho sự xuất sắc trong lâm sàng.",
      tag: "Kỹ thuật chính xác cho cuộc sống",
      cp_title: "Độ chính xác lâm sàng",
      cp_desc: "Các khung sinh học đã được xác nhận.",
      ef_title: "Đạo đức đặt lên hàng đầu",
      ef_desc: "Tuân thủ quyền riêng tư toàn cầu và an ninh bảo mật cao.",
      portal: "Cổng thông tin đăng ký",
      step1: "Bước 1 trên 3: Xác minh danh tính",
      credentials: "Thông tin tài khoản",
      prof_email: "Email công việc",
      prof_email_ph: "Nhập email của bạn",
      access_pw: "Mật khẩu truy cập",
      access_pw_ph: "••••••••",
      personal_details: "Thông tin cá nhân",
      first_name: "Tên",
      first_name_ph: "Nhập tên",
      last_name: "Họ",
      last_name_ph: "Nhập họ",
      affiliation: "Cơ quan công tác",
      affiliation_ph: "Nhập tên cơ quan",
      ecosystems: "Hệ sinh thái nghiên cứu",
      health: "Sức khỏe",
      anti_aging: "Chống lão hóa",
      clinical: "Lâm sàng",
      create_account: "Tạo tài khoản",
      agreement: "Bằng cách tạo tài khoản, bạn đồng ý với Khung Đạo đức và Quy tắc Ứng xử Chuyên nghiệp của chúng tôi."
    },
    footer: {
      brand: "StemLink",
      copyright: "© 2024 StemLink. Kỹ thuật Chính xác cho Cuộc sống.",
      privacy: "Chính sách Bảo mật",
      terms: "Điều khoản Dịch vụ",
      ethics: "Khung Đạo đức",
      offices: "Văn phòng Toàn cầu"
    }
  }
};

const keys = ['ko', 'en', 'ja', 'zh', 'vi'];
keys.forEach(lang => {
  const file = path.join(dictsDir, `${lang}.json`);
  let dict = {};
  if (fs.existsSync(file)) {
    dict = JSON.parse(fs.readFileSync(file, 'utf8'));
  }
  const merged = { ...dict, ...translations[lang] };
  fs.writeFileSync(file, JSON.stringify(merged, null, 2));
});
