import fs from 'fs';
import path from 'path';

const dictsDir = path.resolve(process.cwd(), 'src/i18n/dictionaries');

const fullTranslations = {
  ko: {
    home: {
      philosophy_title: "Brand Philosophy",
      philosophy_subtitle1: "REVA + CELL",
      philosophy_subtitle2: "\"다시 되살리다(REVA) + 세포(CELL)\"",
      philosophy_desc1: "우리는 단순히 기술을 파는 기업이 아닙니다.",
      philosophy_desc2: "\"한 생명을 살리고, 한 영혼을 구원하자\"",
      philosophy_desc3: "는 확고한 사명감 아래 생명 공학의 정점을 지향합니다.",
      global_presence: "Global Presence",
      global_presence_desc: "전 세계 4개국 주요 거점 기반의 혁신 연구 네트워크 구축",
      core_tech_title: "Core Technology",
      core_tech_sub: "기존의 한계를 뛰어넘는 리바셀만의 '자가분화 효소 줄기세포' 기술입니다.",
      comparison_title: "기존 방식 vs RevaCell 자가분화 기술",
      trad_method: "Traditional Method",
      trad_1: "배양 기간 3-4주 소요",
      trad_2: "분리 과정 중 세포 손상",
      trad_3: "복잡한 이동 과정 및 오염 위험",
      reva_innov: "RevaCell Innovation",
      reva_1: "즉석 시술 (Real-time Procedure)",
      reva_2: "독자 효소를 통한 비파괴 분리",
      reva_3: "분화 능력 극대화 (100배 이상)",
      six_adv: "6 Global Advantages",
      adv_1: "독자 효소 원천 기술",
      adv_2: "최첨단 즉석 추출 시스템",
      adv_3: "글로벌 임상 데이터 확보",
      adv_4: "UAE 왕실 케어 공식 파트너",
      adv_5: "10대 중증 질환 특화 솔루션",
      adv_6: "업계 유일 개선 효과 보증제",
      hubs_title: "4 GLOBAL HUBS",
      hubs_sub: "Korea · Japan · China · UAE",
      intl_exp: "International Expansion",
      uae_title: "UAE Royal Care Program",
      uae_desc: "리바셀 바이오는 아랍에미리트(UAE) 왕실과의 파트너십을 통해 최상위 의료 서비스를 제공하고 있습니다. 중동 시장을 거점으로 글로벌 줄기세포 표준을 구축해 나갑니다.",
      uae_item1: "UAE 왕실 전담 의료 기술 지원",
      uae_item2: "글로벌 통합 의료 네트워크 시스템",
      proj_title: "10 Major Research Projects",
      proj_sub: "치료 불가능으로 여겨졌던 질환들에 대한 리바셀의 도전과 결과입니다.",
      p_cancer: "Cancer", p_cancer_sub: "항암 전이 억제",
      p_park: "Parkinson", p_park_sub: "뇌신경 재생",
      p_diab: "Diabetes", p_diab_sub: "인슐린 세포 복원",
      p_heart: "Heart Disease", p_heart_sub: "심근 강화",
      p_arth: "Arthritis", p_arth_sub: "연골 세포 재생",
      p_vision: "Vision Loss", p_vision_sub: "황반변성 치료",
      p_kidney: "Kidney", p_kidney_sub: "신부전 완화",
      p_pulm: "Pulmonary", p_pulm_sub: "폐섬유화 개선",
      p_liver: "Liver", p_liver_sub: "간경변 재생",
      p_aging: "Anti-aging", p_aging_sub: "전신 세포 강화",
      guar_badge: "업계 최초 시행",
      guar_title1: "유전자 검사 기반 ",
      guar_title2: "개선효과 보증제도",
      guar_desc1: "우리는 기술의 정직함을 믿습니다. 시술 전후 유전자 정밀 분석을 통해 객관적인 수치로 개선 효과를 증명하며, 효과 미달 시 ",
      guar_desc2: "100% 환불",
      guar_desc3: "을 약속합니다.",
      step1: "시술 전 유전자 분석",
      step2: "최적화 세포 치료",
      step3: "사후 데이터 검증",
      exp_title: "Global Experts",
      exp1_role: "Executive Director",
      exp1_name: "Kim Mi-jeong", exp1_name_kr: "(김미정)",
      exp1_desc: "줄기세포 자가분화 기술의 상용화를 이끌며, 글로벌 임상 프로토콜 설계 및 왕실 의료 서비스 총괄을 담당하고 있습니다.",
      exp1_p1: "리바셀 바이오 운영 총괄",
      exp1_p2: "글로벌 전략 기획 실장",
      exp2_role: "Chief Science Officer",
      exp2_name: "Joo Gwang-seong", exp2_name_kr: "(주광성)",
      exp2_desc: "자가분화 효소 원천 기술의 발명자로서 리바셀 바이오의 R&D 파트를 이끄는 세계적인 재생 의학 권위자입니다.",
      exp2_p1: "자가분화 효소 기술 특허 보유",
      exp2_p2: "RevaCell 연구소장"
    }
  },
  en: {
    home: {
      philosophy_title: "Brand Philosophy",
      philosophy_subtitle1: "REVA + CELL",
      philosophy_subtitle2: "\"Revive(REVA) + Cell(CELL)\"",
      philosophy_desc1: "We are not just a company selling technology.",
      philosophy_desc2: "\"Save a life, redeem a soul.\"",
      philosophy_desc3: " Under this firm mission, we aim for the pinnacle of bioengineering.",
      global_presence: "Global Presence",
      global_presence_desc: "Establishing an innovative research network based on key hubs in 4 countries worldwide",
      core_tech_title: "Core Technology",
      core_tech_sub: "RevaCell's unique 'Self-Differentiating Enzyme Stem Cell' technology transcends existing limitations.",
      comparison_title: "Traditional Method vs RevaCell Tech",
      trad_method: "Traditional Method",
      trad_1: "Takes 3-4 weeks to culture",
      trad_2: "Cell damage during separation",
      trad_3: "Complex transport and risk of contamination",
      reva_innov: "RevaCell Innovation",
      reva_1: "Real-time Procedure",
      reva_2: "Non-destructive separation via proprietary enzyme",
      reva_3: "Maximized differentiation capacity (100x+)",
      six_adv: "6 Global Advantages",
      adv_1: "Proprietary enzyme technology",
      adv_2: "State-of-the-art instant extraction system",
      adv_3: "Secured global clinical data",
      adv_4: "Official partner of UAE Royal Care",
      adv_5: "Specialized solutions for 10 major diseases",
      adv_6: "Industry's only improvement guarantee program",
      hubs_title: "4 GLOBAL HUBS",
      hubs_sub: "Korea · Japan · China · UAE",
      intl_exp: "International Expansion",
      uae_title: "UAE Royal Care Program",
      uae_desc: "StemLink provides top-tier medical services through a partnership with the UAE Royal Family to establish a global stem cell standard.",
      uae_item1: "Dedicated medical tech support for UAE Royal Family",
      uae_item2: "Global integrated medical network system",
      proj_title: "10 Major Research Projects",
      proj_sub: "RevaCell's challenges and results for diseases once considered incurable.",
      p_cancer: "Cancer", p_cancer_sub: "Anti-metastasis",
      p_park: "Parkinson's", p_park_sub: "Nerve Regeneration",
      p_diab: "Diabetes", p_diab_sub: "Insulin Cell Restoration",
      p_heart: "Heart Disease", p_heart_sub: "Myocardial Strengthening",
      p_arth: "Arthritis", p_arth_sub: "Cartilage Regeneration",
      p_vision: "Vision Loss", p_vision_sub: "Macular Degeneration",
      p_kidney: "Kidney", p_kidney_sub: "Renal Failure Relief",
      p_pulm: "Pulmonary", p_pulm_sub: "Fibrosis Improvement",
      p_liver: "Liver", p_liver_sub: "Cirrhosis Regeneration",
      p_aging: "Anti-aging", p_aging_sub: "Systemic Cell Enhancement",
      guar_badge: "Industry First",
      guar_title1: "Genetic Test-Based ",
      guar_title2: "Improvement Guarantee",
      guar_desc1: "We believe in technological honesty. By proving objective improvement through precise genetic analysis, we promise a ",
      guar_desc2: "100% Refund",
      guar_desc3: " if efficacy is unmet.",
      step1: "Pre-procedure Genetic Analysis",
      step2: "Optimized Cell Therapy",
      step3: "Post-procedure Data Verification",
      exp_title: "Global Experts",
      exp1_role: "Executive Director",
      exp1_name: "Kim Mi-jeong", exp1_name_kr: "",
      exp1_desc: "Leads the commercialization of self-differentiating stem cell tech and directs global clinical protocols and Royal Care services.",
      exp1_p1: "Chief Operating Officer of StemLink",
      exp1_p2: "Head of Global Strategic Planning",
      exp2_role: "Chief Science Officer",
      exp2_name: "Joo Gwang-seong", exp2_name_kr: "",
      exp2_desc: "A globally renowned pioneer in regenerative medicine and inventor of the proprietary self-differentiating enzyme technology.",
      exp2_p1: "Holds patent for Self-Differentiating Enzyme",
      exp2_p2: "Head of RevaCell Research Institute"
    }
  },
  ja: {
    home: {
      philosophy_title: "Brand Philosophy",
      philosophy_subtitle1: "REVA + CELL",
      philosophy_subtitle2: "「蘇らせる(REVA) + 細胞(CELL)」",
      philosophy_desc1: "私たちは単に技術を売る企業ではありません。",
      philosophy_desc2: "「一つの命を救い、一つの魂を救済する」",
      philosophy_desc3: "という確固たる使命感の下、生命工学の頂点を目指しています。",
      global_presence: "Global Presence",
      global_presence_desc: "世界4カ国の主要拠点を基盤とする革新的な研究ネットワークの構築",
      core_tech_title: "Core Technology",
      core_tech_sub: "既存の限界を超えるRevaCell独自の「自己分化酵素幹細胞」技術です。",
      comparison_title: "従来の方法 vs RevaCell技術",
      trad_method: "Traditional Method",
      trad_1: "培養に3〜4週間かかる",
      trad_2: "分離過程での細胞損傷",
      trad_3: "複雑な移動プロセスと汚染リスク",
      reva_innov: "RevaCell Innovation",
      reva_1: "即時施術（Real-time Procedure）",
      reva_2: "独自酵素による非破壊分離",
      reva_3: "分化能力の最大化（100倍以上）",
      six_adv: "6 Global Advantages",
      adv_1: "独自酵素の特許技術",
      adv_2: "最先端の即時抽出システム",
      adv_3: "グローバル臨床データの確保",
      adv_4: "UAE王室ケアの公式パートナー",
      adv_5: "10大重症疾患特化型ソリューション",
      adv_6: "業界唯一の改善効果保証制度",
      hubs_title: "4 GLOBAL HUBS",
      hubs_sub: "Korea · Japan · China · UAE",
      intl_exp: "International Expansion",
      uae_title: "UAE Royal Care Program",
      uae_desc: "StemLinkは、アラブ首長国連邦(UAE)王室とのパートナーシップを通じて最高レベルの医療サービスを提供しています。中東市場を拠点にグローバルな幹細胞標準を構築します。",
      uae_item1: "UAE王室専任医療技術支援",
      uae_item2: "グローバル統合医療ネットワークシステム",
      proj_title: "10 Major Research Projects",
      proj_sub: "治療不可能とされていた疾患に対するRevaCellの挑戦と結果です。",
      p_cancer: "Cancer", p_cancer_sub: "抗がん転移抑制",
      p_park: "Parkinson's", p_park_sub: "脳神経再生",
      p_diab: "Diabetes", p_diab_sub: "インスリン細胞修復",
      p_heart: "Heart Disease", p_heart_sub: "心筋強化",
      p_arth: "Arthritis", p_arth_sub: "軟骨細胞再生",
      p_vision: "Vision Loss", p_vision_sub: "黄斑変性治療",
      p_kidney: "Kidney", p_kidney_sub: "腎不全緩和",
      p_pulm: "Pulmonary", p_pulm_sub: "肺線維症改善",
      p_liver: "Liver", p_liver_sub: "肝硬変再生",
      p_aging: "Anti-aging", p_aging_sub: "全身細胞強化",
      guar_badge: "業界初施行",
      guar_title1: "遺伝子検査に基づく ",
      guar_title2: "改善効果保証制度",
      guar_desc1: "私たちは技術の正直さを信じています。精密な遺伝子分析で客観的な改善効果を証明し、効果に満たない場合は ",
      guar_desc2: "100%返金",
      guar_desc3: "をお約束します。",
      step1: "施術前の遺伝子分析",
      step2: "最適化細胞治療",
      step3: "施術後のデータ検証",
      exp_title: "Global Experts",
      exp1_role: "Executive Director",
      exp1_name: "Kim Mi-jeong", exp1_name_kr: "",
      exp1_desc: "幹細胞自己分化技術の商用化をリードし、グローバル臨床プロトコルと王室医療サービスの統括を担当しています。",
      exp1_p1: "StemLink 運営統括",
      exp1_p2: "グローバル戦略企画室長",
      exp2_role: "Chief Science Officer",
      exp2_name: "Joo Gwang-seong", exp2_name_kr: "",
      exp2_desc: "自己分化酵素源技術の発明者であり、StemLinkのR&D部門を率いる再生医療の世界的権威です。",
      exp2_p1: "自己分化酵素技術特許保有",
      exp2_p2: "RevaCell研究所長"
    }
  },
  zh: {
    home: {
      philosophy_title: "Brand Philosophy",
      philosophy_subtitle1: "REVA + CELL",
      philosophy_subtitle2: "\"复苏(REVA) + 细胞(CELL)\"",
      philosophy_desc1: "我们不仅仅是一家销售技术的公司。",
      philosophy_desc2: "\"拯救一个生命，救赎一个灵魂\"",
      philosophy_desc3: "——带着坚定的使命感，我们立志达到生物工程的巅峰。",
      global_presence: "Global Presence",
      global_presence_desc: "以全球4个国家的核心枢纽为基础，构建创新研究网络",
      core_tech_title: "Core Technology",
      core_tech_sub: "超越现有极限的RevaCell独家“自分化酶干细胞”技术。",
      comparison_title: "传统方法 vs RevaCell技术",
      trad_method: "Traditional Method",
      trad_1: "培养需3-4周时间",
      trad_2: "分离过程中细胞受损",
      trad_3: "运输复杂且有污染风险",
      reva_innov: "RevaCell Innovation",
      reva_1: "实时手术操作",
      reva_2: "通过独家酶进行非破坏性分离",
      reva_3: "分化能力最大化（超过100倍）",
      six_adv: "6 Global Advantages",
      adv_1: "独家酶核心技术",
      adv_2: "最先进的即时提取系统",
      adv_3: "确保全球临床数据",
      adv_4: "阿联酋王室护理官方合作伙伴",
      adv_5: "专治10大重症疾病解决方案",
      adv_6: "业内唯一改善效果保证计划",
      hubs_title: "4 GLOBAL HUBS",
      hubs_sub: "Korea · Japan · China · UAE",
      intl_exp: "International Expansion",
      uae_title: "UAE Royal Care Program",
      uae_desc: "StemLink通过与阿联酋（UAE）王室的合作，提供顶级医疗服务，并以中东市场为枢纽，建立全球干细胞标准。",
      uae_item1: "阿联酋王室专属医疗技术支持",
      uae_item2: "全球综合医疗网络系统",
      proj_title: "10 Major Research Projects",
      proj_sub: "RevaCell针对曾被认为是不治之症的挑战与成果。",
      p_cancer: "Cancer", p_cancer_sub: "抑制癌症转移",
      p_park: "Parkinson's", p_park_sub: "脑神经再生",
      p_diab: "Diabetes", p_diab_sub: "胰岛素细胞修复",
      p_heart: "Heart Disease", p_heart_sub: "强化心肌",
      p_arth: "Arthritis", p_arth_sub: "软骨细胞再生",
      p_vision: "Vision Loss", p_vision_sub: "黄斑变性治疗",
      p_kidney: "Kidney", p_kidney_sub: "缓解肾衰竭",
      p_pulm: "Pulmonary", p_pulm_sub: "改善肺纤维化",
      p_liver: "Liver", p_liver_sub: "肝硬化再生",
      p_aging: "Anti-aging", p_aging_sub: "全身细胞强化",
      guar_badge: "行业首创",
      guar_title1: "基于基因检测的 ",
      guar_title2: "改善效果保证计划",
      guar_desc1: "我们坚信技术的坦诚。通过术前术后基因精准分析提供客观的改善数据证明，如果未达到预期效果，我们承诺",
      guar_desc2: "100% 退款",
      guar_desc3: "。",
      step1: "术前基因分析",
      step2: "优化的细胞治疗",
      step3: "术后数据验证",
      exp_title: "Global Experts",
      exp1_role: "Executive Director",
      exp1_name: "Kim Mi-jeong", exp1_name_kr: "",
      exp1_desc: "主导干细胞自分化技术的商业化，并负责统筹全球临床方案及王室医疗服务。",
      exp1_p1: "StemLink 首席运营官",
      exp1_p2: "全球战略企划室长",
      exp2_role: "Chief Science Officer",
      exp2_name: "Joo Gwang-seong", exp2_name_kr: "",
      exp2_desc: "自分化酶核心技术的发明人，率领RevaCell R&D部门的世界级再生医学权威。",
      exp2_p1: "持有自分化酶技术专利",
      exp2_p2: "RevaCell 研究所所长"
    }
  },
  vi: {
    home: {
      philosophy_title: "Brand Philosophy",
      philosophy_subtitle1: "REVA + CELL",
      philosophy_subtitle2: "\"Hồi sinh(REVA) + Tế bào(CELL)\"",
      philosophy_desc1: "Chúng tôi không chỉ là một công ty bán công nghệ.",
      philosophy_desc2: "\"Cứu một sinh mạng, cứu chuộc một tâm hồn\"",
      philosophy_desc3: " Với sứ mệnh vững chắc này, chúng tôi hướng tới đỉnh cao của kỹ thuật sinh học.",
      global_presence: "Global Presence",
      global_presence_desc: "Xây dựng mạng lưới nghiên cứu đổi mới dựa trên các trung tâm chính ở 4 quốc gia trên toàn cầu",
      core_tech_title: "Core Technology",
      core_tech_sub: "Công nghệ 'Tế bào Gốc Enzyme Tự Biệt hóa' độc quyền của RevaCell vượt qua các giới hạn hiện tại.",
      comparison_title: "Phương pháp truyền thống vs Công nghệ RevaCell",
      trad_method: "Traditional Method",
      trad_1: "Mất 3-4 tuần để nuôi cấy",
      trad_2: "Tổn thương tế bào trong quá trình tách",
      trad_3: "Quá trình vận chuyển phức tạp & rủi ro nhiễm khuẩn",
      reva_innov: "RevaCell Innovation",
      reva_1: "Thủ thuật theo thời gian thực",
      reva_2: "Tách không phá hủy thông qua enzyme độc quyền",
      reva_3: "Tối đa hóa khả năng biệt hóa (hơn 100 lần)",
      six_adv: "6 Global Advantages",
      adv_1: "Công nghệ cốt lõi enzyme độc quyền",
      adv_2: "Hệ thống chiết xuất tức thì tiên tiến nhất",
      adv_3: "Dữ liệu lâm sàng toàn cầu",
      adv_4: "Đối tác chính thức về Chăm sóc Hoàng gia UAE",
      adv_5: "Giải pháp chuyên sâu cho 10 bệnh hiểm nghèo",
      adv_6: "Chương trình đảm bảo cải thiện duy nhất trong ngành",
      hubs_title: "4 GLOBAL HUBS",
      hubs_sub: "Korea · Japan · China · UAE",
      intl_exp: "International Expansion",
      uae_title: "UAE Royal Care Program",
      uae_desc: "StemLink cung cấp dịch vụ y tế hàng đầu thông qua hợp tác với Hoàng gia Các Tiểu vương quốc Ả Rập Thống nhất (UAE), thiết lập tiêu chuẩn tế bào gốc toàn cầu tại thị trường Trung Đông.",
      uae_item1: "Hỗ trợ công nghệ y tế chuyên dụng cho Hoàng gia UAE",
      uae_item2: "Hệ thống mạng lưới y tế tích hợp toàn cầu",
      proj_title: "10 Major Research Projects",
      proj_sub: "Những thách thức và kết quả của RevaCell đối với các bệnh từng được coi là vô phương cứu chữa.",
      p_cancer: "Cancer", p_cancer_sub: "Ức chế di căn",
      p_park: "Parkinson's", p_park_sub: "Tái tạo thần kinh",
      p_diab: "Diabetes", p_diab_sub: "Phục hồi tế bào Insulin",
      p_heart: "Heart Disease", p_heart_sub: "Tăng cường cơ tim",
      p_arth: "Arthritis", p_arth_sub: "Tái tạo tế bào sụn",
      p_vision: "Vision Loss", p_vision_sub: "Điều trị thoái hóa điểm vàng",
      p_kidney: "Kidney", p_kidney_sub: "Giảm nhẹ suy thận",
      p_pulm: "Pulmonary", p_pulm_sub: "Cải thiện xơ phổi",
      p_liver: "Liver", p_liver_sub: "Tái tạo xơ gan",
      p_aging: "Anti-aging", p_aging_sub: "Tăng cường tế bào toàn thân",
      guar_badge: "Lần đầu tiên trong ngành",
      guar_title1: "Dựa trên xét nghiệm di truyền ",
      guar_title2: "Đảm bảo Hiệu quả Cải thiện",
      guar_desc1: "Chúng tôi tin vào sự trung thực của công nghệ. Bằng cách phân tích di truyền chính xác để chứng minh hiệu quả cải thiện qua số liệu khách quan, chúng tôi cam kết ",
      guar_desc2: "Hoàn tiền 100%",
      guar_desc3: " nếu không đạt hiệu quả.",
      step1: "Phân tích di truyền trước thủ thuật",
      step2: "Điều trị tế bào tối ưu hóa",
      step3: "Xác minh dữ liệu sau thủ thuật",
      exp_title: "Global Experts",
      exp1_role: "Executive Director",
      exp1_name: "Kim Mi-jeong", exp1_name_kr: "",
      exp1_desc: "Dẫn dắt thương mại hóa công nghệ tự biệt hóa tế bào gốc và phụ trách thiết kế phác đồ lâm sàng toàn cầu cũng như dịch vụ Chăm sóc Hoàng gia.",
      exp1_p1: "Giám đốc điều hành StemLink",
      exp1_p2: "Trưởng phòng Kế hoạch Chiến lược Toàn cầu",
      exp2_role: "Chief Science Officer",
      exp2_name: "Joo Gwang-seong", exp2_name_kr: "",
      exp2_desc: "Nhà phát minh gốc của công nghệ enzyme tự biệt hóa và là chuyên gia hàng đầu thế giới về y học tái tạo dẫn dắt bộ phận R&D của StemLink.",
      exp2_p1: "Nắm giữ bằng sáng chế enzyme tự biệt hóa",
      exp2_p2: "Viện trưởng Viện nghiên cứu RevaCell"
    }
  }
};

const keys = ['ko', 'en', 'ja', 'zh', 'vi'];
keys.forEach(lang => {
  const file = path.join(dictsDir, `${lang}.json`);
  let dict = {};
  if (fs.existsSync(file)) {
    dict = JSON.parse(fs.readFileSync(file, 'utf8'));
  }
  const merged = { ...dict, home: { ...dict.home, ...fullTranslations[lang].home } };
  fs.writeFileSync(file, JSON.stringify(merged, null, 2));
});
